platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfmanteiga/alpine-bash-curl-jq

inputs:
- name: master
- name: tech-ops

outputs:
- name: code

run:
  path: master/ci/tasks/collect_code.sh
